name: Run DSG and GG tests
on:
  workflow_dispatch:
  push:
  
jobs:
  Run-Tests:
    runs-on: [self-hosted, azure]
    container:
      image: cypress/included:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7

    - name: Install Dependencies with Yarn
      run: yarn

    - name: Run tests with cypress
      run: yarn run-tests
      
    - name: Test Summary
      if: always()
      uses: test-summary/action@v2.3
      with:
        paths: "results/test-output-*.xml"
    
    - name: Upload Test Artifacts
      if: failure()
      uses: actions/upload-artifact@v3.1.2
      with:
        name: cypress-screenshots
        path: ./cypress/screenshots
    
